In [12]:
# TASK 1

import numpy as np
arr1=np.array([[1.0,3.0,5.0],[2.0,4.0,6.0]])
print(arr1)
print(arr1.astype(bool))

[[1. 3. 5.]
 [2. 4. 6.]]
[[ True  True  True]
 [ True  True  True]]


In [14]:
# TASK 2

import numpy as np
arr=np.array([1,3,5,7,9])
b=np.insert(arr, 1, 55)   # posistion 2 means that at second place in array. As array index starts with 0 so At 1 index
print(b)

[ 1 55  3  5  7  9]


In [17]:
# TASK 3

import numpy as np
arr=np.linspace(0, 100, dtype=int)
print(arr)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97 100]


In [27]:
# TASK 4

import numpy as np
mtx1=np.matrix([1,3,5])   # no of rows=1 , no of columns=3 ; 1x3
mtx2=np.matrix([[1,3],[5,7],[9,0]])  # no of rows=3 , no of columns=2 ; 3x2
mul=np.dot(mtx1,mtx2)   # 1 x 3 = 3 x 2 ; no of rows of 1st matrix = no of columns of 2nd matrix
print(mul)

[[61 24]]


In [44]:
#  TASK 5

import numpy as np
arr=np.array([1,2,3,4,5])
num=5
for i in arr:
    if i==num:
        print("Number is present!!")
        break

Number is present!!
